DECLARE @Sql NVARCHAR(500) DECLARE @Cursor CURSOR

SET @Cursor = CURSOR FAST_FORWARD FOR
SELECT DISTINCT sql = 'ALTER TABLE [' + tc2.TABLE_NAME + '] DROP [' + rc1.CONSTRAINT_NAME + ']'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc1
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc2 ON tc2.CONSTRAINT_NAME = rc1.CONSTRAINT_NAME

OPEN @Cursor FETCH NEXT FROM @Cursor INTO @Sql

WHILE (@@FETCH_STATUS = 0)
BEGIN
Exec sp_executesql @Sql
FETCH NEXT FROM @Cursor INTO @Sql
END

CLOSE @Cursor DEALLOCATE @Cursor
GO

EXEC sp_MSforeachtable 'DROP TABLE ?'
GO

CREATE TABLE Division (DivisionId INT NOT NULL IDENTITY PRIMARY KEY, Name varchar(255), Game INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Message (MessageId INT NOT NULL IDENTITY PRIMARY KEY, Content varchar(255), Time INT NOT NULL, Sender INT NOT NULL, Receiver INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Ban (BanId INT NOT NULL IDENTITY PRIMARY KEY, Commentary varchar(255), BannedGeek INT NOT NULL, BanPeriod INT NOT NULL, BanReason INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Ranking (RankingId INT NOT NULL IDENTITY PRIMARY KEY, Standing INT, Game INT NOT NULL, Division INT, Team INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Tournament (TournamentId INT NOT NULL IDENTITY PRIMARY KEY, Initials varchar(255) NOT NULL, Name varchar(255), Rules varchar(255), Slots INT, PlayerNumber INT, Tags varchar(255), RegisteringPeriod INT NOT NULL, PlayingPeriod INT NOT NULL, Game INT NOT NULL, Deleted BIT NOT NULL, Organiser INT NOT NULL);
CREATE TABLE Game (GameId INT NOT NULL IDENTITY PRIMARY KEY, Name varchar(255), AgeLimit INT, GameType INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Team (TeamId INT NOT NULL IDENTITY PRIMARY KEY, Initials varchar(255), Name varchar(255), Tags varchar(255), Captain INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Period (PeriodId INT NOT NULL IDENTITY PRIMARY KEY, Start smalldatetime, Ending smalldatetime, Deleted BIT NOT NULL);
CREATE TABLE Participation (ParticipationId INT NOT NULL IDENTITY PRIMARY KEY, Place INT, Qualified BIT NOT NULL, Team INT NOT NULL, Tournament INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Versus (VersusId INT NOT NULL IDENTITY PRIMARY KEY, Team1 INT, Team2 INT, VersusPeriod INT NOT NULL, Result INT NOT NULL, Tournament INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Reason (ReasonId INT NOT NULL IDENTITY PRIMARY KEY, Name varchar(255), Description varchar(255), Deleted BIT NOT NULL);
CREATE TABLE Stats (StatisticsId INT NOT NULL IDENTITY PRIMARY KEY, Game INT NOT NULL, Team INT NOT NULL, Player INT NOT NULL, WinNumber INT, LoseNumber INT, LifetimeScore INT, Deleted BIT NOT NULL);
CREATE TABLE Round (RoundId INT NOT NULL IDENTITY PRIMARY KEY, Number INT, Versus INT NOT NULL, Result INT, Deleted BIT NOT NULL);
CREATE TABLE Score (ScoreId INT NOT NULL IDENTITY PRIMARY KEY, Result INT NOT NULL, ScoreType INT NOT NULL, Winner INT, Loser INT, Deleted BIT NOT NULL);
CREATE TABLE GameType (GameTypeId INT NOT NULL IDENTITY PRIMARY KEY, Initials varchar(255), Name varchar(255), Description varchar(255), Deleted BIT NOT NULL);
CREATE TABLE ScoreType (ScoreTypeId INT NOT NULL IDENTITY PRIMARY KEY, Initials varchar(255), Name varchar(255), Deleted BIT NOT NULL);
CREATE TABLE Visitor (VisitorId INT NOT NULL IDENTITY PRIMARY KEY, Ip varchar(255) NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Geek (GeekId INT NOT NULL IDENTITY PRIMARY KEY, Username varchar(255) NOT NULL, Name varchar(255), Surname varchar(255), Password varchar(255), Mail varchar(255), Birthdate varchar(10), Deleted BIT NOT NULL);
CREATE TABLE Result (ResultId INT NOT NULL IDENTITY PRIMARY KEY, Loser INT NOT NULL, Winner INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Roles (RoleId INT NOT NULL IDENTITY PRIMARY KEY, Name varchar(255), Deleted BIT NOT NULL);
CREATE TABLE Settings (SettingsId INT NOT NULL IDENTITY PRIMARY KEY, Geek INT NOT NULL, SettingValue INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE Setting (SettingId INT NOT NULL IDENTITY PRIMARY KEY, Name varchar(255), Deleted BIT NOT NULL);
CREATE TABLE RolesGeek (RolesGeekId INT NOT NULL IDENTITY PRIMARY KEY, Role INT NOT NULL, Geek INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE TeamGeek (TeamGeekId INT NOT NULL IDENTITY PRIMARY KEY, Player INT NOT NULL, Team INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE FollowTeam (FollowTeamId INT NOT NULL IDENTITY PRIMARY KEY, Geek INT NOT NULL, Team INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE FollowPlayer (FollowPlayerId INT NOT NULL IDENTITY PRIMARY KEY, Geek INT NOT NULL, Player INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE FollowGame (FollowGameId INT NOT NULL IDENTITY PRIMARY KEY, Geek INT NOT NULL, Game INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE FollowTournament (FollowTournamentId INT NOT NULL IDENTITY PRIMARY KEY, Geek INT NOT NULL, Tournament INT NOT NULL, Deleted BIT NOT NULL);
CREATE TABLE TournamentLog (EntryId INT NOT NULL IDENTITY PRIMARY KEY, Tournament INT NOT NULL, Entry varchar(255), Time INT, Deleted BIT);
CREATE TABLE TournamentTag (TagId INT NOT NULL IDENTITY PRIMARY KEY, Tournament INT NOT NULL, Tag varchar(255), Deleted BIT);
CREATE TABLE TeamTag (TagId INT NOT NULL IDENTITY PRIMARY KEY, Team INT NOT NULL, Tag varchar(255), Deleted BIT); 
CREATE TABLE SettingValues (SettingValuesId INT NOT NULL IDENTITY PRIMARY KEY, Setting INT NOT NULL, Value varchar(255), Preselected BIT NOT NULL, Deleted BIT NOT NULL);